### ISSUE TITLE
[Feature request] Add possibility to provide profile name

### ISSUE THREAD

**Issue by wikijm** [dhondta/AppmemDumper#2]
Hi,

Could you please add the possibility to choose the profile?
In particular, I would like to use a profile I created for Windows 10 x64 19028.

Sincerely,
WikiJM

**Comment by dhondta** [comment]
I don't see what you mean ; in my mind, I remember that the `imageinfo` command executes a KDBG search that gives you a list of valid profiles from which AppmemDumper tries each in order starting from left (continuing to right if error).

Does this search return a Windows 7 profile while the memory image is a Windows 10 ? Or is there an issue with detecting the error on the Windows 7 profile and switching to the next one up to a Windows 10 profile ?

**Comment by dhondta** [comment]
@wikijm  OK, I implemented it anyway. Update incoming... Stay tuned.

**Comment by dhondta** [comment]
@wikijm  Now it should be fixed. Please upgrade `appmemdumper`.

**Comment by wikijm** [comment]
Everything's working perfectly.
Thanks a lot for your time :smiley:
