### ISSUE TITLE
Missing dependancies ?

### ISSUE THREAD

**Issue by k4nfr3** [dhondta/AppmemDumper#5]
root@kali:~/volatility# app-mem-dumper --help
Traceback (most recent call last):
  File "/usr/local/bin/app-mem-dumper", line 59, in <module>
    parser.add_argument("dump", type=file_exists, help="memory dump file path")
NameError: name 'file_exists' is not defined

**Comment by dhondta** [comment]
Hi @k4nfr3 ,
That's a compatibility issue with Tinyscript. I will update this code soon.
Thanks for mentioning.

**Comment by k4nfr3** [comment]
Many thanks :-)
